server:
  servlet:
    context-path: /v1

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    dialect: org.hibernate.dialect.MySQL8Dialect
    format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/tutorDemo
    username: bfp
    password: 02082001
    driver-class-name: com.mysql.cj.jdbc.Driver